---
title: "How to Handle NAs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{How to Handle NAs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

knitr::knit_hooks$set(
  warning = function(x, options) {
    paste(
      '\n\n<div class="alert alert-info">',
      gsub('##', '\n', gsub('Warning: ', '', x)),
      '</div>',
      sep = '\n'
    )
  }
)
```

```{r about-the-article, echo = FALSE, comment = ""}
warning("`ggbraid` offers three different ways to handle `NA`s. This article describes each approach in detail.")
```

```{r setup, message = FALSE}
library(ggplot2)
library(ggbraid)
library(tidyr)
library(dplyr)

set.seed(42)  # for reproducibility

n <- 21

df_long <- tibble(
  x = c(1:n, 1:n),
  y = c(rnorm(n), rnorm(n, mean = 0.5)),
  z = c(rep("a", n), rep("b", n))
)

df_long
```

```{r pivot-wider}
df_wide <- pivot_wider(df_long, names_from = z, values_from = y) %>%
  arrange(x)

df_wide
```

```{r}
p_line <- ggplot() +
  geom_line(aes(x = x, y = y, linetype = z), data = df_long) +
  geom_point(aes(x = x, y = y), data = df_long) +
  guides(linetype = "none", fill = "none") +
  theme_minimal()

p_line
```

```{r}
p_step <- ggplot(df_long) +
  geom_step(aes(x = x, y = y, linetype = z)) +
  geom_point(aes(x = x, y = y)) +
  guides(linetype = "none", fill = "none") +
  theme_minimal()

p_step
```

## Treat `NA`s as gaps

By default, `geom_braid()` handles missing values the same way that `geom_ribbon()` does. 

```{r}
p_line +
  geom_ribbon(
    aes(x = x, ymin = a, ymax = b),
    data = df_wide,
    alpha = 0.3
  )
```

```{r}
p_line +
  geom_braid(
    aes(x = x, ymin = a, ymax = b, fill = a < b),
    data = df_wide,
    alpha = 0.3
  )
```

## Impute `NA`s between observations

`na.impute = TRUE`

```{r}
p_line +
  geom_ribbon(
    aes(x = x, ymin = a, ymax = b),
    data = df_wide,
    alpha = 0.3
  )
```

```{r}
p_line +
  geom_braid(
    aes(x = x, ymin = a, ymax = b, fill = a < b),
    data = df_wide,
    alpha = 0.3,
    method = "line",
    na.impute = TRUE
  )
```

```{r}
p_step +
  geom_braid(
    aes(x = x, ymin = a, ymax = b, fill = a < b),
    data = df_wide,
    alpha = 0.3,
    method = "step",
    na.impute = TRUE
  )
```

## Remove `NA`s

`na.rm = TRUE`
